print("18/4=",18/4)
print("'/' is used for division")
print("18//4=",18//4)
print("'//' drops down to lowest whole number")
print("18%4=",18%4)
print("'%' gives us the remainder")
print("18*4=",18*4)
print("'*' is used for multiplication ")
print("18+4=",18+4)
print("'+' is used for addition")
print("18-4=",18-4)
print("'-' is used for subtraction")
print("5**3=",5**3)
print("'**' indicates raise to..that is 5 to the power 3")
